spring:
  datasource:
    url: jdbc:sqlite:test.db
    driver-class-name: org.sqlite.JDBC
    schema:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

x5456:
  data:
    init:
      db:
        multi:
          - mode: always
            dbType: sqlite3
            appName: db-test